<a href="https://colab.research.google.com/github/itsmeayushipanday/Combined-Cycle-Power-Plant/blob/main/Combined_Cycle_Power_Plant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.12.0'

IMPORTING DATASET

In [3]:
dataset = pd.read_excel("Folds5x2_pp.xlsx")

In [4]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [5]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [6]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


SPLITTING THE DATASET INTO TRAINING SET AND TEST *SET*

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train , X_test , y_train , y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

BUILDING THE ANN

INITIALIZING THE ANN

In [10]:
ann = tf.keras.models.Sequential()

ADDING THE INPUT LAYER AND FIRST HIDDEN LAYER

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation ='relu'))

ADDING THE SECOND HIDDEN LAYER

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation ='relu'))

ADDING THE OUTPUT LAYER

In [14]:
ann.add(tf.keras.layers.Dense(units=1))

TRAINING THE ANN

COMPILING THE ANN

In [15]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

TRAINING THE ANN MODEL ON TRAINING SET

In [16]:
ann.fit(X_train, y_train, epochs = 100, batch_size=32)

Epoch 1/100
240/240 [==============================] - 2s 2ms/step - loss: 206574.0625
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 206356.1250
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 206138.3125
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 205920.8750
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 205703.3281
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 205486.2344
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 205268.9375
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 205052.1406
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 204835.2344
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 204618.5156
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 204402.0469
Epoch 12/100
240/240 [===================

PREDICTING THE RESULT

In [17]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision =2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

60/60 [==============================] - 0s 1ms/step
[[ 23.95 431.23]
 [ 23.95 460.01]
 [ 23.95 461.14]
 ...
 [ 23.95 473.26]
 [ 23.95 438.  ]
 [ 23.95 463.28]]
